### ISSUE TITLE
Zabbix Server 5.4: Availability SNMP  not working

### ISSUE THREAD

**Issue by linuxphone** [jack-valko/Zabbix-Meraki-Discovery#1]
Hi There,
I have install the template and all the devices appear t be showing up, but the SNMP poriton of it still showing the following error:

Timeout while connecting to "192.168.100.24:161".

Any clues why this is happening?

**Comment by jack-valko** [comment]
Hello, and thank you your inquiry.

There are a few reasons why this would happen.  Make sure you can ping your meraki device(s) from the zabbix server or proxy you are monitoring from, and you have made the necessary firewall or access-list changes to support SNMP polling (udp/161) to your meraki device(s) from zabbix. 
 
If that looks ok, verify your meraki device is setup to talk SNMP.  Check out this link for instructions, look under the "Reporting" subsection --> https://documentation.meraki.com/General_Administration/Monitoring_and_Reporting/SNMP_Overview_and_Configuration#Configuration.  The SNMP community string you setup for your meraki devices must match the {$SNMP_COMMUNITY} macro set in zabbix.  If you're still not sure, this link also has instructions on how to poll individual meraki devices with SNMP.

Things should start working at this point.  Let me know if you're still having trouble, and thanks!
