### ISSUE TITLE
Cannot find template "ICMP Ping" for host prototype "{#HOSTNAME}"

### ISSUE THREAD

**Issue by openmindcommunity** [jack-valko/Zabbix-Meraki-Discovery#10]
Getting following error while importing the template- 

Cannot find template "ICMP Ping" for host prototype "{#HOSTNAME}" of discovery rule "Meraki Device Discovery" on "Meraki Cloud Service".

My zabbix version information - 

zabbix_server -V
zabbix_server (Zabbix) 5.4.7
Revision 84dc2ec5dc 28 October 2021, compilation time: Oct 28 2021 11:03:40

Copyright (C) 2021 Zabbix SIA
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it according to
the license. There is NO WARRANTY, to the extent permitted by law.

This product includes software developed by the OpenSSL Project
for use in the OpenSSL Toolkit (http://www.openssl.org/).

Compiled with OpenSSL 1.1.1g FIPS  21 Apr 2020
Running with OpenSSL 1.1.1c FIPS  28 May 2019

**Comment by jack-valko** [comment]
Hello and thank you for reporting this issue.

The Zabbix-Meraki-Template XML references the 'ICMP Ping' host template that ships with 5.4.  If you've upgraded from a previous release it might be named 'Template ICMP Ping', or something else if you've changed the name.  To confirm, click into Configuration->Templates.  In the 'Name' field at the top of the page enter ICMP and click Apply.  Any templates with ICMP in the name will appear.     

To fix this, either edit the Zabbix-Meraki-Template XML file to include the name of your ICMP Ping template, or copy your ICMP template to 'ICMP Ping'.  If you dont have any ICMP templates I would recommend you download and install the [5.4 templates modules](https://git.zabbix.com/projects/ZBX/repos/zabbix/browse/templates/module).

Cheers,
Jack
