### ISSUE TITLE
The handling of cameras during discovery

### ISSUE THREAD

**Issue by ropelletier** [jack-valko/Zabbix-Meraki-Discovery#11]
We have a bunch of cameras on our network which do not support SNMP. How can we change the discovery rule so that if it is a camera, it can be added as an agentless hosts with ping checks only?

**Comment by jack-valko** [comment]
Hello!  What model(s) of meraki cameras do you have?

**Comment by ropelletier** [comment]
We have MV22X, MV32, and MV72X cameras.

**Comment by jack-valko** [comment]
Thanks for this info.  I'll add this feature in the next update that should coincide with the release of Zabbix 6.  Stay tuned.

**Comment by jack-valko** [comment]
This issue is resolved in the latest release.
