### ISSUE TITLE
Error import "Cannot read XML: (41) Specification mandates value for attribute crossorigin [Line: 15 | Column: 76]."

### ISSUE THREAD

**Issue by RG12793** [jack-valko/Zabbix-Meraki-Discovery#15]
Import error running Zabbix v5.4.8
Error "Cannot read XML: (41) Specification mandates value for attribute crossorigin [Line: 15 | Column: 76]."

**Comment by jack-valko** [comment]
Hello and thanks for your input.

I haven't seen this error in test.  Can you let me know how you installed 5.4.8 (sources, packages), what your underlying OS and version is?  Thanks.

**Comment by RG12793** [comment]
Jack, I've seen where it went wrong: download issue: instead of the actual .xml I got a html layout file. Discard the issue. I've got it working now.
