### ISSUE TITLE
Conflict when updating Zabbix-Meraki-Discovery from older Template

### ISSUE THREAD

**Issue by mkruer** [jack-valko/Zabbix-Meraki-Discovery#19]
When importing latest release of Zabbix-Meraki-Discovery into Zabbix 5.4.9, When trying to import I get this error. We currently have is an older Zabbix-Meraki-Discovery that we used from 6 months ago that is currently in use.

Not sure if this is a import issue or if some other changes happened that need to be tested on the older version of Zabbix

```
[Details ](javascript:void(0))Import failed
Two items ("Model Number" and "Model Number") cannot populate one host inventory field "Model", this would lead to a conflict.
```

**Comment by jack-valko** [comment]
Hello and thanks for your report.  I have not sufficiently tested the upgrade/update procedure.  In my test env I usually delete everything and reimport, this may not be a desirable procedure for you. 

You can try to uncheck 'Create new' on Templates and during import. This seemed to work for me when doing an incremental template update.  Since you're upgrading from a release six months ago, your milage may vary.   Let me know if this works for you and I'll update my documentation.

You should keep the old zabbix-meraki-discover.xml file handy in case you want to roll back to a known good state.

Jack

**Comment by mkruer** [comment]
Still running into the same issue.
![Screenshot 2022-02-14 092408](https://user-images.githubusercontent.com/2206117/153882082-0e0a1503-bb95-4e3c-a9d1-fa4cd09101ea.png)

Looking at the code, I am wondering if it is this section below that might be causing the hiccup.  I see the UUID have changed. 
New Code
```
                                <macro>
                                    <macro>{$MODEL}</macro>
                                    <value>{#MODEL}</value>
                                    <description>Model Number</description>
                                </macro>
```
Later in the xml
```
                <item>
                    <uuid>680d423eebe242ed8f89cb398d2c2482</uuid>
                    <name>Model Number</name>
                    <type>SCRIPT</type>
                    <key>model[{$SERIAL}]</key>
                    <delay>1d</delay>
                    <trends>0</trends>
                    <value_type>CHAR</value_type>
                    <params>return '{$MODEL}';</params>
                    <description>Model number reported by devices discovery</description>
                    <inventory_link>MODEL</inventory_link>
                    <tags>
                        <tag>
                            <tag>Application</tag>
                            <value>Device Info</value>
                        </tag>
                    </tags>
                </item>
```

Old Code
```
                                <macro>
                                    <macro>{$MODEL}</macro>
                                    <value>{#MODEL}</value>
                                    <description>Model Number</description>
                                </macro>
```
Later in the xml
```
                <item>
                    <uuid>ce962130fe414890a3ab674cd94bf9d0</uuid>
                    <name>Model Number</name>
                    <type>EXTERNAL</type>
                    <key>echo.something[{$MODEL}]</key>
                    <delay>1d</delay>
                    <trends>0</trends>
                    <value_type>CHAR</value_type>
                    <inventory_link>MODEL</inventory_link>
                    <tags>
                        <tag>
                            <tag>Application</tag>
                            <value>Device Info</value>
                        </tag>
                    </tags>
                </item>
```

**Comment by jack-valko** [comment]
Have you tried changing out the old UUID for the new UUID and updating it?

**Comment by jack-valko** [comment]
Sorry, I got this backwards.  Have you tried replacing the new UUID with the old UUID and rerunning the import?

**Comment by mkruer** [comment]
I swapped the uuids and still getting the same error.

**Comment by mkruer** [comment]
It looks like the version I have that was pulled was on  Jun 29, 2021 Commit 08a599ddf8ac6e5792c7290e60780b93b2e3243f.
Also now that I am looking at the source closer, prior to this last release all the uuid fields were stripped from the code.

**Comment by jack-valko** [comment]
UUIDs weren't a required field in 5.2, when I started development.  It's possible you installed the 5.2 release on 5.4 (perfectly ok according to Zabbix).  I've released a new version that only supports 5.4 and later.   I'll try to repro this issue this weekend and let you know.

**Comment by mkruer** [comment]
I was able to update to commit 58f0802b5562b1e947c2a4a61a7d3aa1f35f980a from  Jul 29, 2021 and that worked ok but going from that to the next one breaks

**Comment by jack-valko** [comment]
This comment came in on another  ....
> So...I attempted to import the file, had an error about an inventory field. Commented out. Another one. Commented out. I then went to import it and came upon the actual cause of the error. Apparently another template that I had installed renamed or changed the ICMP Ping template. Once I restored that, the discovery worked again. Thank you so much for your help. (I know I wasn't the reporter, but maybe it will lead them in the right direction as well)

**Comment by mkruer** [comment]
We were able to resolve the issue. We had to remove the old template and then we where able to install the new one.
