### ISSUE TITLE
Invalid discovery rule value: cannot parse as a valid JSON object: invalid JSON object value starting character at: ']}

### ISSUE THREAD

**Issue by mark-cobra** [jack-valko/Zabbix-Meraki-Discovery#2]
Hello
When I try to execute the discovery I get this error:
Do you know what I do wrong?

![image](https://user-images.githubusercontent.com/58164816/126347501-c3c569df-e90b-4086-a0a9-5b31fb7ceeb6.png)

**Comment by jack-valko** [comment]
Hello and thanks for your inquiry.  From the screen shot you posted, I can't tell if the code you are running came from this repo.  Can you please export the template in question and post it to this thread so I can have a look?

Thanks,  Jack

**Comment by mark-cobra** [comment]
Sorry I used the wrong template, stupid mistake, thanks for your help.
