### ISSUE TITLE
Template does not bring any data

### ISSUE THREAD

**Issue by eliecerserna** [jack-valko/Zabbix-Meraki-Discovery#21]
Greetings.

I do not understand what I am doing wrong, I have used this template but I do not obtain data from the Meraki platform, if there is a connection but it does not bring me any data, please help me since I am new to this world of Zabbix.

I have done an snmpwalk and there is a response from Meraki

I don't want to seem daring, I really appreciate the effort in creating the template and documenting the process, but I'm just starting to work with Zabbix and I've been asked for this urgently.

**Comment by jack-valko** [comment]
Hello!  A few things to consider ...

The template does not snmpwalk the meraki cloud, it uses the web API.  SNMP is only used between your zabbix server or proxy and meraki devices that support SNMP (appliances and switches).

If you've gone through the steps to install on Zabbix 5.4, and have entered your Meraki API key, you will either get data or an error.  Click into the Host 'Meraki Cloud' and look at the discovery rule.  If there is an error with discovery it will appear in the UI.  

You can also use the Test feature inside the Meraki Cloud discovery rule to see if you're getting data back from the Meraki Cloud. You will need to copy and paste in the API key for this.

**Comment by eliecerserna** [comment]
Hola

I thank you for replying.
I have created a macro called {$APIKEY} and in the part where it says value I have added the API Key, but I still do not get data,
I honestly don't know what I'm doing wrong.

**Comment by jack-valko** [comment]
Hi.  What version of Zabbix?  Is this a new install?  Any chance you can delete the templates and host you created and start fresh?  The instructions to install and configure the templates have a lot of detail.

If not post some screenshots of the areas you're working in and I"ll help you the best I can.

**Comment by eliecerserna** [comment]
Hello.
I have configured everything again and now if it shows me the devices, it still does not bring me the data because zabbix is not on the same network as them, so it cannot ping them, I am going to solve this with a vpn between the site where there is zabbix and the devices managed from the console, thank you very much for the effort in creating the template and for the attention to my doubts.
![Dispositivos](https://user-images.githubusercontent.com/12889581/158692412-d2d72e87-4da2-4300-8459-051dd78ac2f3.jpg)

the version of zabbix that I am using is 5.4.10.

I apologize what I write is not so correct, I am using the google translator

**Comment by jack-valko** [comment]
Hello,
I'm glad the template is working.  I'll resolve this issue.  Thank you!!
