### ISSUE TITLE
Does not seem to work with multiple organizations.

### ISSUE THREAD

**Issue by xaviermace86** [jack-valko/Zabbix-Meraki-Discovery#24]
I'm pretty new to Zabbix, so it's certainly possible I'm just doing something wrong.  Running, Zabbix 6.0.5, used the work around for Issue #20 to get the template to import.  However, I seem to only be getting a single (incomplete) host.  Discovery rule shows the following error (numerous times):

Cannot create host: host with the same name "corp-meraki" already exists.

My Meraki portal has 43 organizations, 344 networks.  Not sure how to get a total device count but it's at least a few hundred.  I'm getting a feeling that the template isn't really designed to handle multiple organizations?

**Comment by jack-valko** [comment]
Hello and thank you for your report.

The discovery has been tested successfully on accounts with multiple organizations, although not as many as you have.  What object is 'corp-meraki' in your meraki fleet (org, net, or device)?  Did you add this device by hand by chance?  Zabbix hates duplicate names.  Do you have any duplicate host or network names spread through your multiple orgs?

Are there any errors from the discovery in your zabbix_server log?  If so please post them.  Thanks.

**Comment by jack-valko** [comment]
Closed
