### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by gee456** [jack-valko/Zabbix-Meraki-Discovery#25]
When I try to do an import on 5.4.4 I get

Cannot find template "Interfaces SNMP" for override "Add SNMP Interface Template" of discovery rule "Meraki Device Discovery" on "Meraki Cloud Service".

Let me know if I can provide anything else to help figure this out.

**Comment by jack-valko** [comment]
Hello and thanks for your report. If you have upgraded from an older version of Zabbix, the snmp template has a different name.  You can update it in the Metaki Cloud Service template by navigating into the discovery rule, then into Host Prototype. Look under templates and replace the snmp template with the one you have installed.

**Comment by jack-valko** [comment]
On second thought, I understand now you can’t even import the template so my solution won’t work. Try to edit the template itself and look for the Interfaces SNMP reference, then change that name to your existing snmp template name and try the import again.
