### ISSUE TITLE
API URL incorrect

### ISSUE THREAD

**Issue by Zablove** [jack-valko/Zabbix-Meraki-Discovery#26]
I'm using this template for several months, however it stopped suddenly working, no discovery anymore and no results of last login. As earlier mentioned, I get also the message:
_Cannot execute script: Error: cannot get URL: Timeout was reached.
at [anon] (httprequest.c:323) internal
at [anon] () native strict preventsyield
at [anon] (function:10) preventsyield_
After several hours debugging and also installing a test environment it turns out that the domain api-mp.meraki.com is not longer responding at 443. After changing the URL to api.meraki.com everything works as expected.

**Comment by jack-valko** [comment]
Fixed in latest release
