### ISSUE TITLE
RangeError: execution timeout

### ISSUE THREAD

**Issue by mikeyjoel** [jack-valko/Zabbix-Meraki-Discovery#6]
Getting the following error after executing the 'Meraki Device Discovery' discovery rule:

Cannot execute script: RangeError: execution timeout
at [anon] (duktape.c:75785) internal
at [anon] (function:81) preventsyield

![image](https://user-images.githubusercontent.com/12386094/131923298-ef7ccb04-14d7-4ebe-ae25-69a5e93ed452.png)

Zabbix 5.4.2

Verified that both templates, host and API key were properly configured.

**Comment by jack-valko** [comment]
Hello and thanks for your bug report.

Have you tried raising the timeout value for this discovery rule?  It's default setting is 30s, try increasing it to 300s.  You probably could go as high as 600s safely. 

Do you have a large meraki network?  Is your zabbix instance under load or any contraints?  Let me know how it goes.

Cheers,
Jack

**Comment by mikeyjoel** [comment]
Hi @jack-valko apologies for the delay on this one.

I have tried raising the timeout value to 60 since that's the max I can do in Zabbix.
![Screenshot_2021-11-30_09-28-16](https://user-images.githubusercontent.com/12386094/144065930-82ea91a8-3303-4f9a-a76d-150da24ecf21.png)

The RangeError is still an issue. Let me know if the timeout is supposed to be configured elsewhere.
![Screenshot_2021-11-30_09-29-11](https://user-images.githubusercontent.com/12386094/144066022-fcc137a8-d1f4-458d-b429-21b2760b339d.png)

As for the network, we have 240 networks, 5624 clients.
![Screenshot_2021-11-30_09-29-49](https://user-images.githubusercontent.com/12386094/144066073-08fe6ef1-70b4-4a2d-90e3-eb26d957e145.png)
