### ISSUE TITLE
Cannot execute script: Error: cannot get URL: Timeout was reached

### ISSUE THREAD

**Issue by nmzaw** [jack-valko/Zabbix-Meraki-Discovery#7]
Hi,

I'm getting below error in Load (Item) under Appliance Discovery rule. I'm testing it in Zabbix 6.0 alpha 6

Invalid discovery rule value: cannot parse as a valid JSON object: invalid object format, expected opening character '{' or '[' at: '1'

![Capture](https://user-images.githubusercontent.com/1926535/142565068-4cc69fa8-a4e0-4ce6-9d81-ebf0f096a71e.PNG)

**Comment by jack-valko** [comment]
Hello,
I haven't tested on Zabbix 6 alpha.  Let's me repro this and I'll post an update.
Thanks,
Jack

**Comment by jack-valko** [comment]
Hello and thanks for your patience on this.

I could not repro this issue on Zabbix6 alpha 7.  Can you upgrade to confirm this is still an issue?

Thanks,
Jack

**Comment by nmzaw** [comment]
I ald upgraded to Alpha7 and currently I'm getting below error.

Cannot execute script: Error: cannot get URL: Timeout was reached.
at [anon] (httprequest.c:331) internal
at [anon] () native strict preventsyield
at [anon] (function:10) preventsyield

Unfortunately, Timeout can't raise over 60s
![alpha7_merki](https://user-images.githubusercontent.com/1926535/143984293-042d80b0-c901-4269-8d9c-24fd33bed6a0.JPG)

**Comment by jack-valko** [comment]
Hello,

From the command-line of the zabbix server or proxy where the template is installed, run this command:
```
curl -I -k https://api-mp.meraki.com/
```
You should receive a 302 Found message.  If you do not, there may be a packet filter or firewall between your zabbix server and the meraki api endpoint.  Let me know what happens.

Jack

**Comment by nmzaw** [comment]
We resolved unrechable to https://api-mp.meraki.com and getting back as previous issue. Please check the attach files.

![discover_error](https://user-images.githubusercontent.com/1926535/144546707-bc6106c7-153b-4f37-a819-4fc9d3f355ce.JPG)

![latest_data](https://user-images.githubusercontent.com/1926535/144546711-2141ee98-67a5-428e-8a3e-e969f59bcfb7.JPG)

**Comment by nmzaw** [comment]
Another things is can't import template so I'm creating template manually based on ur template.

**Comment by jack-valko** [comment]
Hi Nay,
If you can't import a template it's going to be impossible for me to troubleshoot a template problem. Please address the situation that's preventing you from installing the template per the instructions in the readme file.  I'd be happy to assist you then.

All the best,
Jack

**Comment by nmzaw** [comment]
I was try it out with Zabbix 5.4 and working as expected. So, I'm trying to manually config items/template in Zabbix 6.0 (alpah) right now. Hope, we can close this issue.
