### ISSUE TITLE
/usr/lib/zabbix/externalscripts/echo.something: [13] Permission denied

### ISSUE THREAD

**Issue by albertvanboerum** [jack-valko/Zabbix-Meraki-Discovery#8]
Hi,

I get an error: /usr/lib/zabbix/externalscripts/echo.something: [13] Permission denied

can you assist me with this?

**Comment by albertvanboerum** [comment]
![image](https://user-images.githubusercontent.com/26927849/143011450-1b3ac3ce-3522-4366-a04c-a83d3658b2bf.png)

**Comment by nmzaw** [comment]
Script should be executable. **chmod +x <script_name>** should be fine

**Comment by albertvanboerum** [comment]
thanks, this is working now
